openapi: 3.1.0
info:
  description: API for the Harmony Speech Engine.
  title: Harmony Speech Engine API
  version: 0.1.0
  x-go-client-name: HarmonySpeechAPI
  x-go-package: harmonyspeech
servers:
- url: /
paths:
  /health:
    get:
      description: Health check endpoint to verify the status of all engine serving
        objects.
      operationId: health_health_get
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Health Health Get
                type: object
          description: Successful Response
      summary: Health
  /version:
    get:
      description: Fetch the Harmony Speech Engine version.
      operationId: show_version_version_get
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                title: Response Show Version Version Get
                type: object
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Show Version
  /v1/audio/speech:
    post:
      description: Generate speech Audio from text.
      operationId: create_speech_v1_audio_speech_post
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TextToSpeechRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TextToSpeechResponse"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Create Speech
  /v1/audio/speech/models:
    get:
      description: Show available speech models.
      operationId: show_available_speech_models_v1_audio_speech_models_get
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelList"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Show Available Speech Models
  /v1/embed/speaker:
    post:
      description: Create a speaker embedding.
      operationId: create_embedding_v1_embed_speaker_post
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmbedSpeakerRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmbedSpeakerResponse"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Create Embedding
  /v1/embed/models:
    get:
      description: Show available embedding models.
      operationId: show_available_embedding_models_v1_embed_models_get
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelList"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Show Available Embedding Models
  /v1/audio/transcriptions:
    post:
      description: Create a transcription from audio.
      operationId: create_transcription_v1_audio_transcriptions_post
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpeechTranscribeRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpeechToTextResponse"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Create Transcription
  /v1/audio/transcriptions/models:
    get:
      description: Show available transcription models.
      operationId: show_available_transcription_models_v1_audio_transcriptions_models_get
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelList"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Show Available Transcription Models
  /v1/voice/convert:
    post:
      description: Convert the voice in an audio file or stream to a desired target
        voice.
      operationId: convert_voice_v1_voice_convert_post
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VoiceConversionRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VoiceConversionResponse"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Convert Voice
  /v1/voice/convert/models:
    get:
      description: Show available voice conversion models.
      operationId: show_available_voice_conversion_models_v1_voice_convert_models_get
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Show Available Voice Conversion Models
  /v1/audio/vad:
    post:
      description: Create a vad from audio.
      operationId: create_vad_v1_audio_vad_post
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DetectVoiceActivityRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetectVoiceActivityResponse"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Create Vad
  /v1/audio/vad/models:
    get:
      description: Show available vad models.
      operationId: show_available_vad_models_v1_audio_vad_models_get
      parameters:
      - explode: false
        in: header
        name: x-api-key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      - explode: false
        in: header
        name: Api-Key
        required: false
        schema:
          nullable: true
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelList"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Show Available Vad Models
components:
  schemas:
    AudioOutputOptions:
      properties:
        format:
          nullable: true
          type: string
        sample_rate:
          nullable: true
          type: integer
        stream:
          nullable: true
          type: boolean
      title: AudioOutputOptions
    DetectVoiceActivityRequest:
      description: |-
        DetectVoiceActivityRequest
        Used to check for human speech in a provided audio file
        Depending on model selection, the caller may need to provide additional params.
      example:
        model: ""
        input_audio: input_audio
        get_timestamps: true
        threshold: 0.8008281904610115
        min_speech_duration_ms: 6
        min_silence_duration_ms: 1
        speech_pad_ms: 5
        return_seconds: true
      properties:
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        input_audio:
          description: "Binary audio data of the reference speaker for synthesizing\
            \ the text, encoded in base64"
          title: Input Audio
          type: string
        get_timestamps:
          description: whether to return the word timestamps. Check model description
            if supported.
          nullable: true
          type: boolean
        threshold:
          description: Speech threshold. Probabilities above this value are considered
            as speech.
          nullable: true
          type: number
        min_speech_duration_ms:
          description: Final speech chunks shorter than this duration (in ms) are
            discarded.
          nullable: true
          type: integer
        min_silence_duration_ms:
          description: Minimum silence duration (in ms) before separating speech chunks.
          nullable: true
          type: integer
        speech_pad_ms:
          description: Speech chunks are padded by this duration (in ms) on each side.
          nullable: true
          type: integer
        return_seconds:
          description: "Whether to return timestamps in seconds (default: samples)."
          nullable: true
          type: boolean
      title: DetectVoiceActivityRequest
    DetectVoiceActivityResponse:
      description: |-
        DetectVoiceActivityResponse
        Result text determined from audio and optional language tag
      example:
        id: id
        model: ""
        created: 0
        speech_activity: false
        timestamps:
        - "{}"
        - "{}"
      properties:
        id:
          title: Id
          type: string
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        created:
          title: Created
          type: integer
        speech_activity:
          default: false
          description: whether speech activity was detected
          title: Speech Activity
          type: boolean
        timestamps:
          description: list of the detected timestamps
          items:
            type: object
          nullable: true
          type: array
          default: null
      title: DetectVoiceActivityResponse
    EmbedSpeakerRequest:
      description: |-
        EmbedSpeakerRequest
        Used to create a Speaker Embedding form a provided audio, which can later be re-used for Text-to-Speech or
        Voice Conversion functionality.
        Please refer to the documentation whether an embedding is compatible between different models.
      example:
        model: ""
        input_audio: input_audio
      properties:
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        input_audio:
          description: "Binary audio data to be processed, encoded in base64"
          title: Input Audio
          type: string
      title: EmbedSpeakerRequest
    EmbedSpeakerResponse:
      description: |-
        EmbedSpeakerResult
        Result Speaker Embedding
      example:
        id: id
        model: ""
        created: 0
        data: data
      properties:
        id:
          title: Id
          type: string
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        created:
          title: Created
          type: integer
        data:
          description: "Speaker embedding data for the audio provided in the initial\
            \ request, encoded in base64"
          title: Data
          type: string
      title: EmbedSpeakerResponse
    GenerationOptions:
      properties:
        seed:
          nullable: true
          type: integer
        style:
          nullable: true
          type: integer
        speed:
          nullable: true
          type: number
        pitch:
          nullable: true
          type: number
        energy:
          nullable: true
          type: number
      title: GenerationOptions
    HTTPValidationError:
      example:
        detail:
        - loc:
          - Location_inner
          - Location_inner
          msg: msg
          type: type
        - loc:
          - Location_inner
          - Location_inner
          msg: msg
          type: type
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          title: Detail
          type: array
          default: null
      title: HTTPValidationError
    LanguageOptions:
      example:
        language: default
        voices:
        - voice: default
          styles:
          - styles
          - styles
        - voice: default
          styles:
          - styles
          - styles
      properties:
        language:
          default: default
          title: Language
          type: string
        voices:
          items:
            $ref: "#/components/schemas/VoiceOptions"
          nullable: true
          type: array
          default: null
      title: LanguageOptions
    ModelCard:
      example:
        id: id
        object: model
        created: 0
        owned_by: harmony-ai-solutions
        languages:
        - language: default
          voices:
          - voice: default
            styles:
            - styles
            - styles
          - voice: default
            styles:
            - styles
            - styles
        - language: default
          voices:
          - voice: default
            styles:
            - styles
            - styles
          - voice: default
            styles:
            - styles
            - styles
        root: root
        parent: parent
      properties:
        id:
          title: Id
          type: string
        object:
          default: model
          title: Object
          type: string
        created:
          title: Created
          type: integer
        owned_by:
          default: harmony-ai-solutions
          title: Owned By
          type: string
        languages:
          items:
            $ref: "#/components/schemas/LanguageOptions"
          nullable: true
          type: array
          default: null
        root:
          nullable: true
          type: string
        parent:
          nullable: true
          type: string
      required:
      - id
      title: ModelCard
    ModelList:
      example:
        object: list
        data:
        - id: id
          object: model
          created: 0
          owned_by: harmony-ai-solutions
          languages:
          - language: default
            voices:
            - voice: default
              styles:
              - styles
              - styles
            - voice: default
              styles:
              - styles
              - styles
          - language: default
            voices:
            - voice: default
              styles:
              - styles
              - styles
            - voice: default
              styles:
              - styles
              - styles
          root: root
          parent: parent
        - id: id
          object: model
          created: 0
          owned_by: harmony-ai-solutions
          languages:
          - language: default
            voices:
            - voice: default
              styles:
              - styles
              - styles
            - voice: default
              styles:
              - styles
              - styles
          - language: default
            voices:
            - voice: default
              styles:
              - styles
              - styles
            - voice: default
              styles:
              - styles
              - styles
          root: root
          parent: parent
      properties:
        object:
          default: list
          title: Object
          type: string
        data:
          items:
            $ref: "#/components/schemas/ModelCard"
          title: Data
          type: array
          default: null
      title: ModelList
    SpeechToTextResponse:
      description: |-
        SpeechToTextResponse
        Result text determined from audio and optional language tag
      example:
        id: id
        model: ""
        created: 0
        text: ""
        language: language
        timestamps:
        - "{}"
        - "{}"
      properties:
        id:
          title: Id
          type: string
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        created:
          title: Created
          type: integer
        text:
          default: ""
          description: text retrieved from the input audio
          title: Text
          type: string
        language:
          description: tag of the detected language
          nullable: true
          type: string
        timestamps:
          description: list of the detected timestamps
          items:
            type: object
          nullable: true
          type: array
          default: null
      title: SpeechToTextResponse
    SpeechTranscribeRequest:
      description: |-
        SpeechTranscribeRequest
        Used to apply ASR on a provided audio file
        Depending on model selection, the caller may need to provide additional params.
        Based on OpenAI STT API; extended for Harmony Speech Engine features.
      example:
        model: ""
        input_audio: input_audio
        get_language: true
        get_timestamps: true
      properties:
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        input_audio:
          description: "Binary audio data of the reference speaker for synthesizing\
            \ the text, encoded in base64"
          title: Input Audio
          type: string
        get_language:
          description: whether to return the source language tag. Check model description
            if supported.
          nullable: true
          type: boolean
        get_timestamps:
          description: whether to return the word timestamps. Check model description
            if supported.
          nullable: true
          type: boolean
      title: SpeechTranscribeRequest
    TextToSpeechRequest:
      description: |-
        TextToSpeechRequest
        Used to trigger a speech generation for the provided text input using the specified model.
        Depending on model selection, the caller may need to provide additional params.
        Based on OpenAI TTS API; extended for Harmony Speech Engine features.
      example:
        model: ""
        input: ""
        mode: ""
        language: language
        voice: voice
        input_audio: input_audio
        input_vad_mode: input_vad_mode
        input_vad_data: input_vad_data
        input_embedding: input_embedding
        generation_options: ""
        output_options: ""
        post_generation_filters:
        - model: ""
          source_audio: source_audio
          target_audio: target_audio
          target_embedding: target_embedding
          generation_options: ""
          output_options: ""
        - model: ""
          source_audio: source_audio
          target_audio: target_audio
          target_embedding: target_embedding
          generation_options: ""
          output_options: ""
      properties:
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        input:
          default: ""
          description: the text to synthesize
          title: Input
          type: string
        mode:
          default: ""
          description: the operation mode for the model to process the request
          title: Mode
          type: string
        language:
          description: language to synthesize. Only if the model supports language
            IDs. Please refer to the model's documentation for which values are availiable.
          nullable: true
          type: string
        voice:
          description: ID of the voice to synthesize. Only if the model supports voice
            IDs. Please refer to the model's documentation for which values are availiable.
          nullable: true
          type: string
        input_audio:
          description: "Binary audio data of the reference speaker for synthesizing\
            \ the text, encoded in base64"
          nullable: true
          type: string
        input_vad_mode:
          description: VAD mode to use in case the provided TTS or VC framework requires
            VAD information for processing
          nullable: true
          type: string
        input_vad_data:
          description: result data from VAD step to be processed in follow-up TTS
            or VC steps
          nullable: true
          type: string
        input_embedding:
          description: "Binary embedding of the reference speaker for synthesizing\
            \ the text, encoded in base64. Faster than providing a target audio file"
          nullable: true
          type: string
        generation_options:
          allOf:
          - $ref: "#/components/schemas/GenerationOptions"
          description: "Options for generating a speech request, see documentation\
            \ for possible values"
          nullable: true
        output_options:
          allOf:
          - $ref: "#/components/schemas/AudioOutputOptions"
          description: "Options for returning the generated audio, see documentation\
            \ for possible values"
          nullable: true
        post_generation_filters:
          description: List of Post-Generation filters to apply to the generated audio.
          items:
            $ref: "#/components/schemas/VoiceConversionRequest"
          nullable: true
          type: array
          default: null
      title: TextToSpeechRequest
    TextToSpeechResponse:
      description: |-
        TextToSpeechResponse
        Extends AudioDataResponse with a request specific ID
      example:
        id: id
        model: ""
        created: 0
        data: data
      properties:
        id:
          title: Id
          type: string
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        created:
          title: Created
          type: integer
        data:
          description: Audio Bytes in requested format of the initial request
          title: Data
          type: string
      title: TextToSpeechResponse
    ValidationError:
      example:
        loc:
        - Location_inner
        - Location_inner
        msg: msg
        type: type
      properties:
        loc:
          items:
            $ref: "#/components/schemas/Location_inner"
          title: Location
          type: array
          default: null
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    VoiceConversionRequest:
      description: |-
        VoiceConversionRequest
        Used to convert the tone or nature of a voice in a specific way.
        Depending on model selection, the caller may need to provide additional params.
      example:
        model: ""
        source_audio: source_audio
        target_audio: target_audio
        target_embedding: target_embedding
        generation_options: ""
        output_options: ""
      properties:
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        source_audio:
          description: "Binary audio data to be processed, encoded in base64"
          title: Source Audio
          type: string
        target_audio:
          description: "Binary audio data of the reference speaker for converting\
            \ the source, encoded in base64"
          nullable: true
          type: string
        target_embedding:
          description: "Binary embedding of the reference speaker for converting the\
            \ source, encoded in base64. Faster than providing a target audio file"
          nullable: true
          type: string
        generation_options:
          allOf:
          - $ref: "#/components/schemas/GenerationOptions"
          description: "Options for generating a speech request, see documentation\
            \ for possible values"
          nullable: true
        output_options:
          allOf:
          - $ref: "#/components/schemas/AudioOutputOptions"
          description: "Options for returning the generated audio, see documentation\
            \ for possible values"
          nullable: true
      title: VoiceConversionRequest
    VoiceConversionResponse:
      description: |-
        VoiceConversionResponse
        Extends AudioDataResponse with a request specific ID
      example:
        id: id
        model: ""
        created: 0
        data: data
      properties:
        id:
          title: Id
          type: string
        model:
          default: ""
          description: the name of the model
          title: Model
          type: string
        created:
          title: Created
          type: integer
        data:
          description: Audio Bytes in requested format of the initial request
          title: Data
          type: string
      title: VoiceConversionResponse
    VoiceOptions:
      example:
        voice: default
        styles:
        - styles
        - styles
      properties:
        voice:
          default: default
          title: Voice
          type: string
        styles:
          items:
            type: string
          nullable: true
          type: array
          default: null
      title: VoiceOptions
    Location_inner:
      anyOf:
      - type: string
      - type: integer
